name: react-app
metadata:
  subscription: ${AZURE_SUBSCRIPTION_ID}
  resourceGroup: ${AZURE_RESOURCE_GROUP}
  location: ${AZURE_LOCATION}
infra:
  bicep: ./infra/main.bicep
services:
  UserPortal:
    project: ../../src/userportal
    host: containerapp
    language: js
    docker:
      context: ../../src/userportal
      path: DOCKERFILE
      registry: ${containerRegistryEndpoint}
    dependsOn:
      - infra