name: react-app
metadata:
  subscription: ${AZURE_SUBSCRIPTION_ID}
  resourceGroup: ${AZURE_RESOURCE_GROUP}
  location: ${AZURE_LOCATION}
infra:
  bicep: ./infra/main.bicep
services:
  UserPortal:
    project: ../../src/spa
    host: containerapp
    language: js
    docker:
      context: ../../src/spa
      path: DOCKERFILE
      registry: $(infra.outputs.containerRegistryEndpoint)
    dependsOn:
      - infra