apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: "{{.Env.SERVICE_API_IMAGE_NAME}}"
          imagePullPolicy: Always
          env:
            - name: AZURE_KEY_VAULT_NAME
              valueFrom:
                secretKeyRef:
                  name: secret-api
                  key: AZURE_KEY_VAULT_NAME
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources: {}
      nodeSelector: {}
      affinity: {}
      tolerations: []
